# Copyright 2018-2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM splintercommunity/splinter-dev:v3 as BUILDER

# Copy over splinter files
COPY Cargo.toml /build/Cargo.toml
COPY cli/Cargo.toml /build/cli/Cargo.toml
COPY client/Cargo.toml /build/client/Cargo.toml
COPY libsplinter/build.rs /build/libsplinter/build.rs
COPY libsplinter/Cargo.toml /build/libsplinter/Cargo.toml
COPY libsplinter/protos /build/libsplinter/protos
COPY splinterd/Cargo.toml /build/splinterd/Cargo.toml
COPY services/health/Cargo.toml /build/services/health/Cargo.toml
COPY services/scabbard/src /build/services/scabbard/src

# Copy over example Cargo.toml files
COPY examples/gameroom/cli/Cargo.toml \
     /build/examples/gameroom/cli/Cargo.toml
COPY examples/gameroom/daemon/Cargo.toml \
     /build/examples/gameroom/daemon/Cargo.toml
COPY examples/gameroom/database/Cargo.toml \
     /build/examples/gameroom/database/Cargo.toml
COPY examples/private_counter/cli/Cargo.toml \
     /build/examples/private_counter/cli/Cargo.toml
COPY examples/private_counter/service/Cargo.toml \
     /build/examples/private_counter/service/Cargo.toml
COPY examples/private_xo/Cargo.toml /build/examples/private_xo/Cargo.toml

# Copy over source files
COPY examples/private_counter/protos /build/examples/private_counter/protos
COPY examples/private_counter/service /build/examples/private_counter/service
COPY libsplinter /build/libsplinter

# Build the package
WORKDIR /build/examples/private_counter/service
ARG REPO_VERSION
ARG CARGO_ARGS
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS

# Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# -------------=== private_xo docker build ===-------------
FROM ubuntu:bionic

ARG CARGO_ARGS
RUN echo "CARGO_ARGS = '$CARGO_ARGS'" > CARGO_ARGS

COPY --from=BUILDER /build/target/debian/private-counter-service*.deb /tmp
COPY --from=BUILDER /commit-hash /commit-hash

RUN apt-get update \
 && dpkg --unpack /tmp/private-counter-service*.deb \
 && apt-get -f -y install

EXPOSE 8000

CMD ["private-counter"]
