# Copyright 2018-2021 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.7"

services:

  splinter-node-0:
    image: splinterd:latest
    build:
        context: ../..
        dockerfile: ./splinterd/Dockerfile-installed-${DISTRO}
        args:
          - REPO_VERSION=${REPO_VERSION}
    expose:
      - 8043
      - 8044
    volumes:
      - ./demo_state:/splinter_state
      - ./node_registry:/node_registry
    command: >
      bash -c "
        splinterd -vv \
                --transport raw \
                --storage yaml \
                --service-endpoint 0.0.0.0:8043 \
                --network-endpoint 0.0.0.0:8044 \
                --node-id 012 \
                --registry-file /node_registry/nodes.yaml
      "
    environment:
      SPLINTER_STATE_DIR: /splinter_state

  splinter-node-1:
    image: splinterd:latest
    build:
        context: ../..
        dockerfile: ./splinterd/Dockerfile-installed-${DISTRO}
        args:
          - REPO_VERSION=${REPO_VERSION}
    expose:
      - 8045
      - 8046
    volumes:
      - ./demo_state:/splinter_state
      - ./node_registry:/node_registry
    command: >
      bash -c "
        splinterd -vv \
                --transport raw \
                --storage yaml \
                --service-endpoint 0.0.0.0:8045 \
                --network-endpoint 0.0.0.0:8046 \
                --node-id 345 \
                --registry-file /node_registry/nodes.yaml
      "
    environment:
      SPLINTER_STATE_DIR: /splinter_state

  private-xo-service-a:
    image: private-xo:latest
    container_name: private-xo-service-a
    build:
        context: ../..
        dockerfile: ./examples/private_xo/Dockerfile-installed-${DISTRO}
        args:
          - REPO_VERSION=${REPO_VERSION}
    expose:
        - 8000
    ports:
        - "8008:8000"
    command: >
        bash -c "
          sleep 10;
          private-xo -vv \
                      --bind 0.0.0.0:8000 \
                      --circuit alpha \
                      --service-id service_a \
                      --verifier service_b \
                      --connect splinter-node-0:8043
        "

  private-xo-service-b:
    image: private-xo:latest
    container_name: private-xo-service-b
    build:
        context: ../..
        dockerfile: ./examples/private_xo/Dockerfile-installed-${DISTRO}
        args:
          - REPO_VERSION=${REPO_VERSION}
    expose:
        - 8000
    ports:
        - "8009:8000"
    command: >
        bash -c "
          sleep 10;
          private-xo -vv \
                      --bind 0.0.0.0:8000 \
                      --circuit alpha \
                      --service-id service_b \
                      --verifier service_a \
                      --connect splinter-node-1:8045
        "

  xo-shell:
    image: hyperledger/sawtooth-shell:1.1
    container_name: xo-shell
    command: |
        bash -c "
          sawtooth keygen &&
          tail -f /dev/null
        "
