# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

node_id = "2456qwerty"

# Endpoint used for service to daemon communication.
service_endpoint = "127.0.0.1:8043"

# Endpoint used for daemon to daemon communication.
network_endpoint = "127.0.0.1:8044"

# A list of splinter nodes the daemon will automatically
# connect to on start up.
peers = []

# The type of storage that should be used to store circuit state. Option are
# currently "yaml" or "memory"
storage = "memory"

# Which transport type this splinterd node supports. Options are "raw" or "tls"
transport = "tls"

# Rest api address.
bind = "0.0.0.0:8085"

# Node Registry file
registry_file = "/node_registry/nodes.yaml"
