# Copyright 2018-2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM splintercommunity/splinter-dev:v3 as BUILDER

# Copy over splinter files
COPY Cargo.toml /build/Cargo.toml
COPY cli/Cargo.toml /build/cli/Cargo.toml
COPY client/Cargo.toml /build/client/Cargo.toml
COPY libsplinter/build.rs /build/libsplinter/build.rs
COPY libsplinter/Cargo.toml /build/libsplinter/Cargo.toml
COPY libsplinter/protos /build/libsplinter/protos
COPY splinterd/Cargo.toml /build/splinterd/Cargo.toml
COPY services/health/Cargo.toml /build/services/health/Cargo.toml
COPY services/scabbard/src /build/services/scabbard/src

# Copy over example Cargo.toml files
COPY examples/gameroom/cli/Cargo.toml \
     /build/examples/gameroom/cli/Cargo.toml
COPY examples/gameroom/daemon/Cargo.toml \
     /build/examples/gameroom/daemon/Cargo.toml
COPY examples/gameroom/database/Cargo.toml \
     /build/examples/gameroom/database/Cargo.toml
COPY examples/private_counter/cli/Cargo.toml \
     /build/examples/private_counter/cli/Cargo.toml
COPY examples/private_counter/service/Cargo.toml \
     /build/examples/private_counter/service/Cargo.toml
COPY examples/private_xo/Cargo.toml /build/examples/private_xo/Cargo.toml

# Copy over source files

COPY cli /build/cli
COPY examples/gameroom/cli /build/examples/gameroom/cli
COPY examples/gameroom/database /build/examples/gameroom/database
COPY examples/gameroom/daemon/ /build/examples/gameroom/daemon
COPY libsplinter /build/libsplinter
COPY splinterd /build/splinterd

# Build the gameroomd package
WORKDIR /build/examples/gameroom/daemon
ARG REPO_VERSION
ARG CARGO_ARGS
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS

# Build the gameroom-cli package
WORKDIR /build/examples/gameroom/cli
ARG REPO_VERSION
ARG CARGO_ARGS
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS

# Build splinter-cli
WORKDIR /build/cli
ARG REPO_VERSION
ARG CARGO_ARGS
RUN sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${REPO_VERSION}\"/" Cargo.toml
RUN cargo deb --deb-version $REPO_VERSION $CARGO_ARGS
RUN mv /build/target/debian/splinter-cli*.deb /tmp

# Log the commit hash
COPY .git/ /tmp/.git/
WORKDIR /tmp
RUN git rev-parse HEAD > /commit-hash

# -------------=== gameroomd docker build ===-------------
FROM ubuntu:bionic

ARG CARGO_ARGS
RUN echo "CARGO_ARGS = '$CARGO_ARGS'" > CARGO_ARGS

RUN apt-get update \
 && apt-get install -y \
    curl \
    postgresql-client \
    unzip

COPY --from=BUILDER /build/target/debian/gameroom*.deb /tmp/
COPY --from=BUILDER /tmp/splinter-*.deb /tmp/
COPY --from=BUILDER /commit-hash /commit-hash

RUN apt-get update \
 && dpkg --unpack /tmp/gameroom*.deb \
 && dpkg --unpack /tmp/splinter*.deb \
 && apt-get -f -y install

# Fetch the XO smart contract
RUN curl -OLsS https://build.sawtooth.me/job/Sawtooth-Hyperledger/job/sawtooth-sdk-rust/job/master/lastSuccessfulBuild/artifact/build/scar/*zip*/scar.zip

RUN unzip -oj scar.zip \
 && tar -xvf xo_*.scar \
 && rm scar.zip xo_*.scar \
 && mv xo-tp-rust.wasm /var/lib/gameroomd/xo-tp-rust.wasm

CMD ["gameroomd"]
