name: "Label PRs"
on:
  pull_request_target:
    types: [ opened, ready_for_review ]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GH_TOKEN }}"
